language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build

services:
  - postgresql

before_script:
  - psql -c 'create database bankdb;' -U postgres

before_install:
  - npm install
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: travis_kat

notifications:
  email:
    - kspanerio@gmail.com
    - atbaclado@up.edu.ph