language: node_js
node_js:
  - "7"

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c 'create database bankdb;' -U postgres

before_install:
  - npm install

notifications:
  email:
    - kspanerio@gmail.com
    - atbaclado@gmail.com

deploy:
  skip_cleanup: true

jobs:
  include:
    deploy: &heroku
        provider: heroku
        app: blooming-retreat-41751
        api_key: b1880a05-488c-460f-805f-1bb4fcd0833a
