language: node_js
node_js:
  - "7"

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c 'create database bankdb;' -U postgres

before_install:
  - npm install


notifications:
  email:
    - kspanerio@gmail.com
    - atbaclado@up.edu.ph

