sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.6"
  chrome: stable

node_js:
  - "7"

services:
  - postgresql

after_install:
  - npm rebuild node-sass
  - ./node_modules/protractor/bin/webdriver-manager update
  
before_script:
  - psql -c 'create database bankdb;' -U postgres

jobs:
  include:
    deploy: &heroku
        provider: heroku
        app: blooming-retreat-41751
        api_key: b1880a05-488c-460f-805f-1bb4fcd0833a
        
notifications:
  email:
    - paneriokat@gmail.com
    - honeydrops149@gmail.com
  on_success: always
  on_failure: always