language: node_js
node_js:
  - "7"

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c 'create database bankdb;' -U postgres

before_install:
  - npm install

deploy:
  skip_cleanup: true

notifications:
  email:
    - kspanerio@gmail.com

jobs:
  include:
    deploy: &heroku
        provider: heroku
        app: salty-depths-79809
        api_key: b1880a05-488c-460f-805f-1bb4fcd0833a